name: Deploy to Cloud Run (WIF)

on:
  push:
    branches: [main]

env:
  PROJECT_ID: deeployed-case
  REGION: us-central1
  SERVICE: deeployed-webhook-server
  REGISTRY_HOST: us-central1-docker.pkg.dev
  REPOSITORY: webhooks

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write # required for WIF
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Authenticate to Google Cloud (WIF)
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
          service_account: ${{ secrets.SERVICE_ACCOUNT }}

      - name: Set up gcloud
        uses: google-github-actions/setup-gcloud@v2
        with:
          project_id: ${{ env.PROJECT_ID }}

      - name: Configure Docker auth for Artifact Registry
        run: |
          gcloud auth configure-docker $REGISTRY_HOST --quiet

      - name: Build and push container image
        run: |
          IMAGE_URI=$REGISTRY_HOST/$PROJECT_ID/$REPOSITORY/$SERVICE:latest
          echo "IMAGE_URI=$IMAGE_URI" >> $GITHUB_ENV
          docker build -t $IMAGE_URI .
          docker push $IMAGE_URI

      - name: Deploy to Cloud Run
        run: |
          IMAGE_URI=${IMAGE_URI:-$REGISTRY_HOST/$PROJECT_ID/$REPOSITORY/$SERVICE:latest}
          gcloud run deploy $SERVICE \
            --image $IMAGE_URI \
            --region $REGION \
            --platform managed \
            --allow-unauthenticated \
            --timeout 300 \
            --port 8080 \
            --set-secrets GITHUB_APP_ID=GITHUB_APP_ID:latest,GITHUB_APP_PRIVATE_KEY=GITHUB_APP_PRIVATE_KEY:latest,GITHUB_WEBHOOK_SECRET=GITHUB_WEBHOOK_SECRET:latest,OPENAI_API_KEY=OPENAI_API_KEY:latest

